#include <iostream>
#include <cmath>

bool isPrime(int n) {
    for (int i = 2; i <= sqrt(n); i++) {
        if (n % i == 0) {
            return false;
        }
    }
    return true;
}

bool isSemiPrime(int n) {
    for (int i = 2; i <= sqrt(n); i++) {
        if (isPrime(i) && isPrime(n / i)) {
            return true;
        }
    }
    return false;
}

int main() {
    for (int i = 1; i <= 100; i++) {
        if (isSemiPrime(i)) {
            std::cout << i << " ";
        }
    }
    return 0;
}
